repos:
  - repo: local
    hooks:
      - id: clang-format
        name: Formatear Codigo C
        entry: clang-format -i --style=file
        language: system
        types: [c, header]
      - id: make-all
        name: Verificar Compilacion
        entry: make all
        language: system
        always_run: true
        pass_filenames: false
      - id: trailing-whitespace
        name: Quitar espacios al final
        entry: sed -i 's/[[:space:]]*$//'
        language: system
        types: [text]